package Exception;

public class TestTryCatch {
	
	public static void main(String[] args) {
		
		int a = 0;
		int b = 18;
		int c = 15;
		int d = 20;
        try {		
	    double div = b/a*d-c;
        }       catch(ArithmeticException e) {
        	System.out.println("wrong method");
        }
        }}

		
	
	
	


